### ISSUE TITLE
del

### ISSUE THREAD

**Issue by usergitxub** [Soju06/kernelLoader#1]
del

**Comment by Soju06** [comment]
This essentially indicates that the service couldn't be started.
To identify the root cause, more detailed information such as driver details and the argument values used in the kernelLoader are required.

There could be various reasons, but here are some typical examples:
1. The issue may arise when an unsigned driver is directly loaded without bypassing.
    Try using the `--ignore-signatures` flag.
2. Financial security software or anti-cheat systems might have blocked the driver initiation.
3. The starting point of the driver, the `DriverEntry` function, might not have returned `STATUS_SUCCESS`.

**Comment by usergitxub** [comment]
I'm trying to load a regular cheat engine driver, how can I actually fix it?

**Comment by usergitxub** [comment]
Yes, the --ignore-signatures command helped me, thank you
